font_family             JetBrainsMono Nerd Font
font_size               8.0
modify_font cell_height 120%
disable_ligatures       no
enable_audio_bell       no
shell                   zsh
shell_integration       disabled
cursor_shape            block
url_style               curly
window_padding_width    15
background_opacity      0.6
confirm_os_window_close 0
sync_to_monitor         no
allow_remote_control    yes 
listen_on unix:@mykitty

##colors
#kitty-themes/themes/snazzy.conf
background            #000000
foreground            #c2c7f0
cursor                #dff9fb
cursor_text_color     #141526
selection_background  #2a2b45
selection_foreground  #ffffff
color0                #25263d
color8                #57587e
color1                #ffb3ba
color9                #ffc6cb
color2                #baffc9
color10               #cbfecf
color3                #ffffba
color11               #fffff0
color4                #bae1ff
color12               #ccdfff
color5                #e8bcf0
color13               #f3cfff
color6                #b2ece1
color14               #d1f5ee
color7                #e2e4f0
color15               #ffffff
active_border_color   #bae1ff
inactive_border_color #25263d
