require("modules.autostart")
require("modules.keybinds")
require("modules.monitors")
require("modules.windowrules")
require("modules.appearance")
require("modules.animations")
require("modules.input")
require("modules.enviroments")
